apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gdnd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gdnd.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "gdnd.config" . | nindent 4 }}
