{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gdnd.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gdnd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "gdnd.selectorLabels" . | nindent 4 }}
{{- end }}
